### ISSUE TITLE
这是为啥

### ISSUE THREAD

**Issue by ewfubwefwe** [thunder-sec/T00lsSign#1]
![image](https://user-images.githubusercontent.com/91933542/165722762-520e48ed-b8e2-47a3-838c-cf9ebb41ea1a.png)

**Comment by thunder-sec** [comment]
创建云函数环境使用python3.6，你用的3.7的吧！

**Comment by ewfubwefwe** [comment]
![image](https://user-images.githubusercontent.com/91933542/165724950-e6176316-e52d-4a4c-9c3a-c54dc3658c61.png)
就是3.6

**Comment by thunder-sec** [comment]
没事，这行代码是登录创建会话的，不影响执行。

**Comment by ewfubwefwe** [comment]
![image](https://user-images.githubusercontent.com/91933542/165726886-5fb892e5-2a62-403e-8204-d1add193bf8c.png)
测试不成功呀

**Comment by thunder-sec** [comment]
忘了说明了，创建函数时将超时时间设为最长 即 900s。

**Comment by ewfubwefwe** [comment]
改了还是不成功



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月28日(周四) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thunder-sec/T00lsSign] 这是为啥 (Issue #1)




 
忘了说明了，创建函数时将超时时间设为最长 即 900s。

**Comment by thunder-sec** [comment]
只填写access_token，不是整个webhook url

**Comment by ewfubwefwe** [comment]
我这边测试成功了，但是刚刚群还是没有通知












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thunder-sec/T00lsSign"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月30日(星期六) 凌晨0:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thunder-sec/T00lsSign] 这是为啥 (Issue #1)





 
只填写access_token，不是整个webhook url

**Comment by ewfubwefwe** [comment]
![image](https://user-images.githubusercontent.com/91933542/166088781-6dd5ff86-dfcc-4a06-9c6f-5e8f2c964e07.png)
还是不行
![image](https://user-images.githubusercontent.com/91933542/166088805-9d51ea60-d867-4399-a688-d99f736efe1e.png)

**Comment by thunder-sec** [comment]
去掉access_token=

**Comment by ewfubwefwe** [comment]
![image](https://user-images.githubusercontent.com/91933542/168263227-844ee428-1979-4ab7-8d0b-0e01a6a4dbd0.png)
测试不成功

**Comment by ewfubwefwe** [comment]
啥原因？

**Comment by thunder-sec** [comment]
更新代码
